title: UPRM CMS Software Documentation
description: Tutorial for setting up in the UPRM-CMS group
permalink: /:categories/:title

content_type: Analysis Software Tutorial
use_authors: true #Set this to false to disable showing post authors

brand_logo: logo.png
brand_name: UPRM-CMS
header: Analysis Software Tutorial
subheader: Hand-on tutorial

meta_image: odin-meta.png

# Social Links
github_username: YarelisAcevedo
email: yarelis.acevedo@upr.edu
linkedin_page: https://www.linkedin.com/in/yarelis-acevedo-550b7644/

# Navivation
nav_item_one: Qualifiers
nav_item_one_link: 

nav_item_two: Getting an account
nav_item_two_link: https://twitter.com/TheTeaGuns

nav_item_three: #
nav_item_three_link: #

nav_button: #
nav_button_link: #

# More Help
help_one_title: Python tutorials
help_one_content: Basic Python tutorials
help_one_button: Python
help_one_link: #

help_two_title: C++ tutorials
help_two_content: Basic C++ tutorials
help_two_button: C++
help_two_link: #

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-last-modified-at

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#


sass:
  sass_dir:          _scss
  style:            :compressed
